# Generated by Django 6.0.3 on 2026-03-05 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='google_scholar',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='user',
            name='orc_id',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='researchgate',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='user',
            name='scopus_id',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='wos_id',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
