# Generated by Django 6.0.3 on 2026-03-05 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_user_google_scholar_user_orc_id_user_researchgate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_user',
            field=models.BooleanField(default=True),
        ),
    ]
