# Generated by Django 6.0.3 on 2026-03-05 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_user_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='journal_ids',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='user',
            name='journal_links',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='user',
            name='satbayev_profile_url',
            field=models.URLField(blank=True),
        ),
    ]
