# Generated by Django 6.0.3 on 2026-03-15

import django.db.models.deletion
from django.db import migrations, models


DEFAULT_INSTITUTE_NAME = "Общий институт"


def forwards_fill_department_institute(apps, schema_editor):
    Department = apps.get_model("account", "Department")
    Institute = apps.get_model("account", "Institute")

    institute_ids_by_university: dict[int, int] = {}
    departments = Department.objects.all().only("id", "university_id", "institute_id")
    for department in departments.iterator():
        university_id = getattr(department, "university_id", None)
        if not university_id:
            continue

        institute_id = institute_ids_by_university.get(university_id)
        if institute_id is None:
            institute, _ = Institute.objects.get_or_create(
                university_id=university_id,
                name=DEFAULT_INSTITUTE_NAME,
            )
            institute_id = institute.id
            institute_ids_by_university[university_id] = institute_id

        Department.objects.filter(pk=department.pk).update(institute_id=institute_id)


def backwards_fill_department_university(apps, schema_editor):
    Department = apps.get_model("account", "Department")
    departments = Department.objects.select_related("institute").all().only("id", "institute_id")
    for department in departments.iterator():
        institute = getattr(department, "institute", None)
        if not institute:
            continue
        Department.objects.filter(pk=department.pk).update(university_id=institute.university_id)


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0005_user_journal_ids_user_journal_links_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Institute",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=200)),
                (
                    "university",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="institutes",
                        to="account.university",
                    ),
                ),
            ],
            options={
                "unique_together": {("name", "university")},
            },
        ),
        migrations.AddField(
            model_name="department",
            name="institute",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="departments",
                to="account.institute",
            ),
        ),
        migrations.RunPython(
            forwards_fill_department_institute,
            backwards_fill_department_university,
        ),
        migrations.RemoveField(
            model_name="department",
            name="university",
        ),
        migrations.AlterField(
            model_name="department",
            name="institute",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="departments",
                to="account.institute",
            ),
        ),
    ]
