# Generated by Django 6.0.3 on 2026-03-24 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_alter_user_gender_alter_user_orc_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='google_scholar',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='user',
            name='researchgate',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='user',
            name='satbayev_profile_url',
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
