# Generated by Django 6.0.3 on 2026-03-12

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CeleryTaskLog",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("task_id", models.CharField(db_index=True, max_length=64, unique=True)),
                ("parent_task_id", models.CharField(blank=True, db_index=True, max_length=64)),
                ("task_name", models.CharField(blank=True, db_index=True, max_length=255)),
                ("queue_name", models.CharField(blank=True, max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("RECEIVED", "Received"),
                            ("STARTED", "Started"),
                            ("PROGRESS", "Progress"),
                            ("SUCCESS", "Success"),
                            ("FAILURE", "Failure"),
                            ("RETRY", "Retry"),
                            ("REVOKED", "Revoked"),
                            ("SKIPPED", "Skipped"),
                        ],
                        db_index=True,
                        default="PENDING",
                        max_length=16,
                    ),
                ),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("DEBUG", "Debug"),
                            ("INFO", "Info"),
                            ("WARNING", "Warning"),
                            ("ERROR", "Error"),
                        ],
                        db_index=True,
                        default="INFO",
                        max_length=10,
                    ),
                ),
                ("message", models.CharField(blank=True, max_length=500)),
                ("result", models.JSONField(blank=True, default=dict)),
                ("meta", models.JSONField(blank=True, default=dict)),
                ("progress_current", models.PositiveIntegerField(blank=True, null=True)),
                ("progress_total", models.PositiveIntegerField(blank=True, null=True)),
                ("progress_percent", models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ("object_id", models.CharField(blank=True, db_index=True, max_length=120)),
                ("object_type", models.CharField(blank=True, db_index=True, max_length=80)),
                ("username", models.CharField(blank=True, max_length=150)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("duration_ms", models.PositiveBigIntegerField(blank=True, null=True)),
                ("worker_hostname", models.CharField(blank=True, max_length=255)),
                ("traceback_text", models.TextField(blank=True)),
                ("is_finished", models.BooleanField(db_index=True, default=False)),
                ("is_success", models.BooleanField(db_index=True, default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ("-updated_at", "-id"),
                "indexes": [
                    models.Index(fields=["task_name"]),
                    models.Index(fields=["status"]),
                    models.Index(fields=["created_at"]),
                    models.Index(fields=["object_type", "object_id"]),
                ],
            },
        ),
    ]
