# Generated by Django 6.0.3 on 2026-03-07 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='synonym',
            name='example',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='synonym',
            name='example_image',
            field=models.ImageField(blank=True, null=True, upload_to='synonym_examples/'),
        ),
        migrations.AlterField(
            model_name='document',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='file_type',
            field=models.CharField(choices=[('pdf', 'PDF'), ('docx', 'DOCX'), ('txt', 'TXT'), ('excel', 'Excel'), ('pptx', 'PowerPoint'), ('other', 'Other')], default='other', max_length=50),
        ),
    ]
