# Generated by Django 6.0.3 on 2026-03-07 11:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0003_alter_document_options_document_is_deleted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='generated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_documents', to='document.documentgenerator'),
        ),
    ]
