# Generated by Django 6.0.3 on 2026-03-14 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0004_document_generated_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentgenerator',
            name='page',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
