"""
Django settings for project project.

Generated by 'django-admin startproject' using Django 6.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import importlib.util
import os
from pathlib import Path
from urllib.parse import urlparse

from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
load_dotenv(BASE_DIR / '.env')
LOG_DIR = BASE_DIR / 'logs'
LOG_DIR.mkdir(parents=True, exist_ok=True)


def _as_bool(value: str | None, default: bool = False) -> bool:
    if value is None:
        return default
    return str(value).strip().lower() in {'1', 'true', 'yes', 'on'}


def _as_int(value: str | None, default: int = 0) -> int:
    if value is None:
        return default
    try:
        parsed = int(str(value).strip())
    except (TypeError, ValueError):
        return default
    return parsed if parsed >= 0 else default


def _as_float(value: str | None, default: float = 0.0) -> float:
    if value is None:
        return default
    try:
        parsed = float(str(value).strip())
    except (TypeError, ValueError):
        return default
    return parsed if parsed > 0 else default


def _resolved_db_host() -> str:
    dev_mode = _as_bool(os.getenv('DEV_MODE'), default=True)
    if dev_mode:
        return (os.getenv('DEV_DB_HOST') or 'db').strip()
    return (os.getenv('PROD_DB_HOST') or os.getenv('DB_HOST') or '192.168.1.222').strip()


def _database_settings_from_env() -> dict:
    database_url = (os.getenv('DATABASE_URL') or '').strip()
    if database_url:
        parsed = urlparse(database_url)
        if parsed.scheme in {'postgres', 'postgresql'}:
            return {
                'ENGINE': 'django.db.backends.postgresql',
                'NAME': (parsed.path or '/postgres').lstrip('/'),
                'USER': parsed.username or '',
                'PASSWORD': parsed.password or '',
                'HOST': parsed.hostname or _resolved_db_host(),
                'PORT': str(parsed.port or 5432),
                'CONN_MAX_AGE': _as_int(os.getenv('DB_CONN_MAX_AGE'), default=60),
            }

    db_engine = (os.getenv('DB_ENGINE') or '').strip().lower()
    if (
        db_engine in {'postgres', 'postgresql'}
        or os.getenv('POSTGRES_DB')
        or os.getenv('DB_NAME')
        or os.getenv('DEV_MODE')
    ):
        return {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': os.getenv('DB_NAME', os.getenv('POSTGRES_DB', 'su_science')),
            'USER': os.getenv('DB_USER', os.getenv('POSTGRES_USER', 'su_science')),
            'PASSWORD': os.getenv('DB_PASSWORD', os.getenv('POSTGRES_PASSWORD', 'postgres')),
            'HOST': _resolved_db_host(),
            'PORT': os.getenv('DB_PORT', '5432'),
            'CONN_MAX_AGE': _as_int(os.getenv('DB_CONN_MAX_AGE'), default=60),
        }

    return {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY')
# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DEBUG', 'True') == 'True'

ALLOWED_HOSTS = ['*']

AUTH_USER_MODEL = 'account.User'

# Application definition

INSTALLED_APPS = [
    'jazzmin',
    'channels',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_celery_beat',
    'core',
    'main',
    'account',
    'document',
    'llm',
    'django_extensions',
]

if importlib.util.find_spec('daphne') is not None:
    INSTALLED_APPS.insert(0, 'daphne')

JAZZMIN_SETTINGS = {
    "site_title": "SU Scholar Admin",
    "site_header": "SU Scholar",
    "site_brand": "SU Scholar",
    "welcome_sign": "SU Scholar әкімшілік панелі",
}

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
]
STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"
# DEV convenience:
# - by default with DEBUG=True, CSRF checks are disabled (allow all origins, including ngrok)
# - override via .env: DISABLE_CSRF_CHECKS=0 to re-enable checks
DISABLE_CSRF_CHECKS = _as_bool(os.getenv('DISABLE_CSRF_CHECKS'), default=DEBUG)
if DISABLE_CSRF_CHECKS:
    MIDDLEWARE = [mw for mw in MIDDLEWARE if mw != 'django.middleware.csrf.CsrfViewMiddleware']

ROOT_URLCONF = 'project.urls'
ASGI_APPLICATION = 'project.asgi.application'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'main.context_processors.layout_navigation',
            ],
        },
    },
]

WSGI_APPLICATION = 'project.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': _database_settings_from_env()
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

DEFAULT_CHARSET = "utf-8"
FILE_CHARSET = "utf-8"


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'
DOCK_EDITOR_URL = os.getenv('DOCK_EDITOR_URL', 'http://192.168.1.3:8080')
APP_PUBLIC_URL = os.getenv('APP_PUBLIC_URL', '')
_onlyoffice_jwt_secret_raw = os.getenv('ONLYOFFICE_JWT_SECRET', 'onlyoffice-local-secret' if DEBUG else '')
ONLYOFFICE_JWT_SECRET = _onlyoffice_jwt_secret_raw.replace('$$', '$')
LLM_API = os.getenv('LLM_API', 'http://localhost:11434/v1')
LLM_API_KEY = os.getenv('LLM_API_KEY', '')
LLM_MODEL = os.getenv('LLM_MODEL', 'gpt-oss:20b')
PROJECT_AGENT_MODEL_FAST = os.getenv('PROJECT_AGENT_MODEL_FAST', 'gpt-oss:20b')
PROJECT_AGENT_MODEL_MIDDLE = os.getenv('PROJECT_AGENT_MODEL_MIDDLE', 'qwen3:30b')
PROJECT_AGENT_MODEL_HIGH = os.getenv('PROJECT_AGENT_MODEL_HIGH', 'gpt-oss:120b')
PROJECT_AGENT_LLM_TIMEOUT_FAST = _as_int(os.getenv('PROJECT_AGENT_LLM_TIMEOUT_FAST'), default=120)
PROJECT_AGENT_LLM_TIMEOUT_MIDDLE = _as_int(os.getenv('PROJECT_AGENT_LLM_TIMEOUT_MIDDLE'), default=300)
PROJECT_AGENT_LLM_TIMEOUT_HIGH = _as_int(os.getenv('PROJECT_AGENT_LLM_TIMEOUT_HIGH'), default=1200)
PROJECT_AGENT_LLM_MAX_RETRIES_FAST = _as_int(os.getenv('PROJECT_AGENT_LLM_MAX_RETRIES_FAST'), default=2)
PROJECT_AGENT_LLM_MAX_RETRIES_MIDDLE = _as_int(os.getenv('PROJECT_AGENT_LLM_MAX_RETRIES_MIDDLE'), default=3)
PROJECT_AGENT_LLM_MAX_RETRIES_HIGH = _as_int(os.getenv('PROJECT_AGENT_LLM_MAX_RETRIES_HIGH'), default=4)
PROJECT_AGENT_NODE_URL = os.getenv('PROJECT_AGENT_NODE_URL', 'http://node:3000')
PROJECT_AGENT_PUBLIC_NODE_URL = os.getenv('PROJECT_AGENT_PUBLIC_NODE_URL', '')
PROJECT_AGENT_INTERNAL_APP_BASE_URL = os.getenv('PROJECT_AGENT_INTERNAL_APP_BASE_URL', 'http://web:8000')
LLM_CONNECT_TIMEOUT = _as_float(os.getenv('LLM_CONNECT_TIMEOUT'), default=15.0)
LLM_READ_TIMEOUT = _as_float(os.getenv('LLM_READ_TIMEOUT'), default=120.0)
LLM_WRITE_TIMEOUT = _as_float(os.getenv('LLM_WRITE_TIMEOUT'), default=30.0)
LLM_POOL_TIMEOUT = _as_float(os.getenv('LLM_POOL_TIMEOUT'), default=30.0)
LLM_MAX_RETRIES = _as_int(os.getenv('LLM_MAX_RETRIES'), default=2)

# Email (SMTP)
EMAIL_BACKEND = os.getenv('EMAIL_BACKEND', 'django.core.mail.backends.smtp.EmailBackend')
EMAIL_HOST = os.getenv('GOOGLE_SMTP_HOST', os.getenv('GOOGLE_SMTP_HOST', 'smtp.gmail.com'))
EMAIL_PORT = int(os.getenv('GOOGLE_SMTP_PORT', '587'))
EMAIL_HOST_USER = os.getenv('GOOGLE_SMTP_EMAIL', '')
EMAIL_HOST_PASSWORD = os.getenv('GOOGLE_STMP_PASSWORD', os.getenv('GOOGLE_SMTP_PASSWORD', ''))
EMAIL_USE_TLS = _as_bool(os.getenv('GOOGLE_SMTP_USE_TLS'), default=True)
EMAIL_USE_SSL = _as_bool(os.getenv('GOOGLE_SMTP_USE_SSL'), default=False)
EMAIL_TIMEOUT = int(os.getenv('GOOGLE_SMTP_TIMEOUT', '30'))
DEFAULT_FROM_EMAIL = os.getenv('DEFAULT_FROM_EMAIL', EMAIL_HOST_USER or 'no-reply@su-science.local')
SERVER_EMAIL = os.getenv('SERVER_EMAIL', DEFAULT_FROM_EMAIL)

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'standard': {
            'format': '%(asctime)s [%(levelname)s] %(name)s: %(message)s',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'standard',
        },
        'file': {
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': LOG_DIR / 'app.log',
            'maxBytes': 5 * 1024 * 1024,
            'backupCount': 5,
            'formatter': 'standard',
            'encoding': 'utf-8',
        },
    },
    'root': {
        'handlers': ['console', 'file'],
        'level': 'INFO',
    },
    'loggers': {
        'django': {
            'handlers': ['console', 'file'],
            'level': 'INFO',
            'propagate': False,
        },
        'main': {
            'handlers': ['console', 'file'],
            'level': 'INFO',
            'propagate': False,
        },
        'document': {
            'handlers': ['console', 'file'],
            'level': 'INFO',
            'propagate': False,
        },
        'utils': {
            'handlers': ['console', 'file'],
            'level': 'INFO',
            'propagate': False,
        },
    },
}

# Celery
CELERY_BROKER_URL = os.getenv('CELERY_BROKER_URL', 'redis://127.0.0.1:6379/0')
CELERY_RESULT_BACKEND = os.getenv('CELERY_RESULT_BACKEND', CELERY_BROKER_URL)
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = TIME_ZONE
CELERY_BEAT_SCHEDULER = 'django_celery_beat.schedulers:DatabaseScheduler'
CELERY_BROKER_CONNECTION_RETRY_ON_STARTUP = True
CELERY_WORKER_CONCURRENCY = _as_int(os.getenv('CELERY_WORKER_CONCURRENCY'), default=15)
CELERY_WORKER_PREFETCH_MULTIPLIER = _as_int(os.getenv('CELERY_WORKER_PREFETCH_MULTIPLIER'), default=1)

# WebSockets (Django Channels)
CHANNELS_USE_REDIS = _as_bool(os.getenv('CHANNELS_USE_REDIS'), default=True)
CHANNELS_REDIS_URL = os.getenv('CHANNELS_REDIS_URL', CELERY_BROKER_URL)

if CHANNELS_USE_REDIS:
    CHANNEL_LAYERS = {
        'default': {
            'BACKEND': 'channels_redis.core.RedisChannelLayer',
            'CONFIG': {
                'hosts': [CHANNELS_REDIS_URL],
            },
        }
    }
else:
    CHANNEL_LAYERS = {
        'default': {
            'BACKEND': 'channels.layers.InMemoryChannelLayer',
        }
    }
