# Generated by Django 6.0.3 on 2026-03-05 10:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('orcid', models.CharField(blank=True, max_length=30)),
                ('affiliations', models.TextField(blank=True)),
                ('is_department_staff', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='DepartmentArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='IndexingDatabase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('project_type', models.CharField(choices=[('gf', 'ГФ'), ('pcf', 'ПЦФ'), ('contract', 'хоздоговор'), ('other', 'другое')], default='other', max_length=20)),
                ('contract_number', models.CharField(blank=True, max_length=100)),
                ('funding_source', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='PublicationType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('kind', models.CharField(choices=[('journal', 'Journal'), ('conference', 'Conference'), ('book', 'Book/Collection'), ('other', 'Other')], default='journal', max_length=20)),
                ('character', models.CharField(choices=[('scientific_journal', 'Научный журнал'), ('conf_proceedings', 'Материалы конференции'), ('collection', 'Сборник'), ('monograph', 'Монография'), ('other', 'Другое')], default='scientific_journal', max_length=30)),
                ('publisher', models.CharField(blank=True, max_length=200)),
                ('issn', models.CharField(blank=True, max_length=20)),
                ('isbn', models.CharField(blank=True, max_length=20)),
                ('conference_name', models.CharField(blank=True, max_length=300)),
                ('conference_country', models.CharField(blank=True, max_length=100)),
                ('conference_city', models.CharField(blank=True, max_length=100)),
                ('series', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_id', models.CharField(blank=True, max_length=50, unique=True)),
                ('title_original', models.CharField(max_length=500)),
                ('year', models.PositiveIntegerField()),
                ('publication_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('accepted', 'Accepted'), ('published', 'Published')], default='published', max_length=20)),
                ('accepted_date', models.DateField(blank=True, null=True)),
                ('volume', models.CharField(blank=True, max_length=30)),
                ('issue', models.CharField(blank=True, max_length=30)),
                ('pages', models.CharField(blank=True, max_length=50)),
                ('article_number', models.CharField(blank=True, max_length=50)),
                ('total_pages', models.PositiveIntegerField(blank=True, null=True)),
                ('doi', models.CharField(blank=True, max_length=120)),
                ('url_publisher', models.URLField(blank=True)),
                ('url_open_access', models.URLField(blank=True)),
                ('quartile', models.CharField(blank=True, max_length=2)),
                ('quartile_year', models.PositiveIntegerField(blank=True, null=True)),
                ('citations_count', models.PositiveIntegerField(default=0)),
                ('citations_updated_at', models.DateField(blank=True, null=True)),
                ('open_access', models.BooleanField(default=False)),
                ('oa_type', models.CharField(blank=True, choices=[('', '—'), ('gold', 'Gold'), ('green', 'Green'), ('hybrid', 'Hybrid')], default='', max_length=10)),
                ('keywords', models.TextField(blank=True)),
                ('report_period', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.departmentarea')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_publications', to=settings.AUTH_USER_MODEL)),
                ('indexing', models.ManyToManyField(blank=True, to='main.indexingdatabase')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.language')),
            ],
        ),
        migrations.CreateModel(
            name='PublicationAuthor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField()),
                ('role', models.CharField(choices=[('first', 'First author'), ('corresponding', 'Corresponding author'), ('coauthor', 'Co-author')], default='coauthor', max_length=20)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.author')),
                ('publication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.publication')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('publication', 'author')},
            },
        ),
        migrations.AddField(
            model_name='publication',
            name='authors',
            field=models.ManyToManyField(related_name='publications', through='main.PublicationAuthor', to='main.author'),
        ),
        migrations.CreateModel(
            name='PublicationFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('pdf', 'PDF'), ('acceptance', 'Acceptance letter / proof'), ('other', 'Other')], default='pdf', max_length=20)),
                ('file', models.FileField(upload_to='publication_files/')),
                ('description', models.CharField(blank=True, max_length=200)),
                ('publication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='main.publication')),
            ],
        ),
        migrations.AddField(
            model_name='publication',
            name='pub_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.publicationtype'),
        ),
        migrations.CreateModel(
            name='RepositoryLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('label', models.CharField(blank=True, max_length=100)),
                ('publication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repo_links', to='main.publication')),
            ],
        ),
        migrations.AddField(
            model_name='publication',
            name='tags',
            field=models.ManyToManyField(blank=True, to='main.tag'),
        ),
        migrations.AddField(
            model_name='publication',
            name='venue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='publications', to='main.venue'),
        ),
        migrations.CreateModel(
            name='PublicationIdentifier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_type', models.CharField(choices=[('scopus_eid', 'Scopus EID'), ('wos_accession', 'WoS Accession'), ('rinz', 'РИНЦ'), ('gs', 'Google Scholar'), ('other', 'Other')], max_length=30)),
                ('value', models.CharField(max_length=200)),
                ('publication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='identifiers', to='main.publication')),
            ],
            options={
                'unique_together': {('publication', 'id_type', 'value')},
            },
        ),
        migrations.CreateModel(
            name='PublicationProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.project')),
                ('publication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.publication')),
            ],
            options={
                'unique_together': {('publication', 'project')},
            },
        ),
        migrations.CreateModel(
            name='VenueMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric', models.CharField(choices=[('sjr', 'SJR'), ('citescore', 'CiteScore'), ('jif', 'JIF (Impact Factor)'), ('snip', 'SNIP')], max_length=20)),
                ('year', models.PositiveIntegerField()),
                ('value', models.DecimalField(decimal_places=4, max_digits=10)),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='main.venue')),
            ],
            options={
                'unique_together': {('venue', 'metric', 'year')},
            },
        ),
    ]
