# Generated by Django 6.0.3 on 2026-03-14 07:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('content', models.TextField()),
                ('publication_date', models.DateField()),
                ('related_projects', models.ManyToManyField(blank=True, to='main.project')),
                ('related_publications', models.ManyToManyField(blank=True, to='main.publication')),
            ],
        ),
        migrations.CreateModel(
            name='NewsMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='news_media/')),
                ('description', models.CharField(blank=True, max_length=200)),
                ('media_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video'), ('other', 'Other')], default='image', max_length=50)),
                ('news_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='main.newsitem')),
            ],
        ),
    ]
