# Generated by Django 6.0.3 on 2026-03-18 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_author_name_initials_author_name_normalized_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicationfile',
            name='source_url',
            field=models.URLField(blank=True, db_index=True, max_length=500),
        ),
    ]
