# Generated by Django 6.0.3 on 2026-04-15 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0005_documentgenerator_page'),
        ('main', '0007_project_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='documents',
            field=models.ManyToManyField(blank=True, related_name='projects', to='document.document'),
        ),
    ]
