from django.urls import path

from .views import (
    document_detail,
    document_edit_page,
    document_file,
    documents_collection,
    generator_file,
    generator_create,
    generator_detail,
    generator_edit_page,
    generator_onlyoffice_callback,
    generator_onlyoffice_config,
    onlyoffice_callback,
    onlyoffice_config,
    synonym_create,
    synonym_detail,
    synonyms_export,
    synonyms_import,
)


urlpatterns = [
    path("documents", documents_collection, name="document_main"),
    path("documents/", documents_collection),
    path("documents/<int:pk>", document_detail, name="document_detail"),
    path("documents/<int:pk>/", document_detail),
    path("documents/<int:pk>/edit", document_edit_page, name="document_edit"),
    path("documents/<int:pk>/edit/", document_edit_page),
    path("generators/create", generator_create, name="generator_create"),
    path("generators/create/", generator_create),
    path("synonyms/export", synonyms_export, name="synonyms_export"),
    path("synonyms/export/", synonyms_export),
    path("synonyms/import", synonyms_import, name="synonyms_import"),
    path("synonyms/import/", synonyms_import),
    path("synonyms/create", synonym_create, name="synonym_create"),
    path("synonyms/create/", synonym_create),
    path("synonyms/<int:pk>", synonym_detail, name="synonym_detail"),
    path("synonyms/<int:pk>/", synonym_detail),
    path("generators/<int:pk>", generator_detail, name="generator_detail"),
    path("generators/<int:pk>/", generator_detail),
    path("generators/<int:pk>/edit", generator_edit_page, name="generator_edit"),
    path("generators/<int:pk>/edit/", generator_edit_page),
    path("onlyoffice/config/<int:pk>", onlyoffice_config, name="onlyoffice_config"),
    path("onlyoffice/config/<int:pk>/", onlyoffice_config),
    path("onlyoffice/generator/config/<int:pk>", generator_onlyoffice_config, name="generator_onlyoffice_config"),
    path("onlyoffice/generator/config/<int:pk>/", generator_onlyoffice_config),
    path("files/<int:pk>", document_file, name="document_file"),
    path("files/<int:pk>/", document_file),
    path("generator-files/<int:pk>", generator_file, name="generator_file"),
    path("generator-files/<int:pk>/", generator_file),
    path("onlyoffice/callback/<int:pk>", onlyoffice_callback, name="onlyoffice_callback"),
    path("onlyoffice/callback/<int:pk>/", onlyoffice_callback),
    path("onlyoffice/generator/callback/<int:pk>", generator_onlyoffice_callback, name="generator_onlyoffice_callback"),
    path("onlyoffice/generator/callback/<int:pk>/", generator_onlyoffice_callback),
]
