# Generated by Django 6.0.3 on 2026-03-16 07:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Чат открыто')),
                ('title', models.CharField(max_length=500, verbose_name='Тема чата')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(verbose_name='Текст')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Отправлено')),
                ('sended_from', models.CharField(choices=[('user', 'пользователь'), ('bot', 'бот')], default='пользователь', verbose_name='Отправитель')),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='llm.chatsession')),
            ],
        ),
    ]
