# Generated by Django 6.0.3 on 2026-03-16 07:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('llm', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chatsession',
            options={'ordering': ('-updated', '-id')},
        ),
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ('created', 'id')},
        ),
        migrations.AddField(
            model_name='chatsession',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated at'),
        ),
        migrations.AlterField(
            model_name='chatsession',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='chatsession',
            name='title',
            field=models.CharField(default='New dialog', max_length=500, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='chatsession',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='llm_chat_sessions', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='message',
            name='body',
            field=models.TextField(verbose_name='Text'),
        ),
        migrations.AlterField(
            model_name='message',
            name='chat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='llm.chatsession', verbose_name='Chat'),
        ),
        migrations.AlterField(
            model_name='message',
            name='created',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='message',
            name='sended_from',
            field=models.CharField(choices=[('user', 'User'), ('bot', 'Assistant')], db_index=True, default='user', max_length=16, verbose_name='Sender'),
        ),
    ]
