# Generated by Django 6.0.3 on 2026-03-19 05:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('llm', '0002_alter_chatsession_options_alter_message_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatShareLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(db_index=True, max_length=96, unique=True, verbose_name='Referral token')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Is active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('expires_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Expires at')),
                ('last_opened_at', models.DateTimeField(blank=True, null=True, verbose_name='Last opened at')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='llm_chat_share_links', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='share_links', to='llm.chatsession', verbose_name='Shared chat session')),
            ],
            options={
                'ordering': ('-created_at', '-id'),
            },
        ),
        migrations.CreateModel(
            name='ChatShareImport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='share_imports', to='llm.chatsession', verbose_name='Imported session')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='llm_chat_share_imports', to=settings.AUTH_USER_MODEL, verbose_name='Imported by')),
                ('share_link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imports', to='llm.chatsharelink', verbose_name='Share link')),
            ],
            options={
                'ordering': ('-created_at', '-id'),
                'constraints': [models.UniqueConstraint(fields=('share_link', 'user'), name='unique_llm_share_import_per_user')],
            },
        ),
    ]
