# Generated by Django 6.0.3 on 2026-04-14 16:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('llm', '0003_chatsharelink_chatshareimport'),
        ('main', '0005_publicationfile_source_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatsession',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='llm_chat_sessions', to='main.project', verbose_name='project_chat_sessions'),
        ),
    ]
